# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client/CMakeFiles /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client/applications/Task1/CMakeFiles/progress.marks
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/Task1/all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/Task1/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/Task1/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/Task1/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
applications/Task1/CMakeFiles/test.dir/rule:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/Task1/CMakeFiles/test.dir/rule
.PHONY : applications/Task1/CMakeFiles/test.dir/rule

# Convenience name for target.
test: applications/Task1/CMakeFiles/test.dir/rule

.PHONY : test

# fast build rule for target.
test/fast:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f applications/Task1/CMakeFiles/test.dir/build.make applications/Task1/CMakeFiles/test.dir/build
.PHONY : test/fast

# Convenience name for target.
applications/Task1/CMakeFiles/task1ex1.dir/rule:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/Task1/CMakeFiles/task1ex1.dir/rule
.PHONY : applications/Task1/CMakeFiles/task1ex1.dir/rule

# Convenience name for target.
task1ex1: applications/Task1/CMakeFiles/task1ex1.dir/rule

.PHONY : task1ex1

# fast build rule for target.
task1ex1/fast:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f applications/Task1/CMakeFiles/task1ex1.dir/build.make applications/Task1/CMakeFiles/task1ex1.dir/build
.PHONY : task1ex1/fast

# Convenience name for target.
applications/Task1/CMakeFiles/task1ex2.dir/rule:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/Task1/CMakeFiles/task1ex2.dir/rule
.PHONY : applications/Task1/CMakeFiles/task1ex2.dir/rule

# Convenience name for target.
task1ex2: applications/Task1/CMakeFiles/task1ex2.dir/rule

.PHONY : task1ex2

# fast build rule for target.
task1ex2/fast:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f applications/Task1/CMakeFiles/task1ex2.dir/build.make applications/Task1/CMakeFiles/task1ex2.dir/build
.PHONY : task1ex2/fast

# Convenience name for target.
applications/Task1/CMakeFiles/task1ex3.dir/rule:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/Task1/CMakeFiles/task1ex3.dir/rule
.PHONY : applications/Task1/CMakeFiles/task1ex3.dir/rule

# Convenience name for target.
task1ex3: applications/Task1/CMakeFiles/task1ex3.dir/rule

.PHONY : task1ex3

# fast build rule for target.
task1ex3/fast:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f applications/Task1/CMakeFiles/task1ex3.dir/build.make applications/Task1/CMakeFiles/task1ex3.dir/build
.PHONY : task1ex3/fast

# Convenience name for target.
applications/Task1/CMakeFiles/task1ex32.dir/rule:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f CMakeFiles/Makefile2 applications/Task1/CMakeFiles/task1ex32.dir/rule
.PHONY : applications/Task1/CMakeFiles/task1ex32.dir/rule

# Convenience name for target.
task1ex32: applications/Task1/CMakeFiles/task1ex32.dir/rule

.PHONY : task1ex32

# fast build rule for target.
task1ex32/fast:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f applications/Task1/CMakeFiles/task1ex32.dir/build.make applications/Task1/CMakeFiles/task1ex32.dir/build
.PHONY : task1ex32/fast

task1ex1.o: task1ex1.c.o

.PHONY : task1ex1.o

# target to build an object file
task1ex1.c.o:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f applications/Task1/CMakeFiles/task1ex1.dir/build.make applications/Task1/CMakeFiles/task1ex1.dir/task1ex1.c.o
.PHONY : task1ex1.c.o

task1ex1.i: task1ex1.c.i

.PHONY : task1ex1.i

# target to preprocess a source file
task1ex1.c.i:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f applications/Task1/CMakeFiles/task1ex1.dir/build.make applications/Task1/CMakeFiles/task1ex1.dir/task1ex1.c.i
.PHONY : task1ex1.c.i

task1ex1.s: task1ex1.c.s

.PHONY : task1ex1.s

# target to generate assembly for a file
task1ex1.c.s:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f applications/Task1/CMakeFiles/task1ex1.dir/build.make applications/Task1/CMakeFiles/task1ex1.dir/task1ex1.c.s
.PHONY : task1ex1.c.s

task1ex2.o: task1ex2.c.o

.PHONY : task1ex2.o

# target to build an object file
task1ex2.c.o:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f applications/Task1/CMakeFiles/task1ex2.dir/build.make applications/Task1/CMakeFiles/task1ex2.dir/task1ex2.c.o
.PHONY : task1ex2.c.o

task1ex2.i: task1ex2.c.i

.PHONY : task1ex2.i

# target to preprocess a source file
task1ex2.c.i:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f applications/Task1/CMakeFiles/task1ex2.dir/build.make applications/Task1/CMakeFiles/task1ex2.dir/task1ex2.c.i
.PHONY : task1ex2.c.i

task1ex2.s: task1ex2.c.s

.PHONY : task1ex2.s

# target to generate assembly for a file
task1ex2.c.s:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f applications/Task1/CMakeFiles/task1ex2.dir/build.make applications/Task1/CMakeFiles/task1ex2.dir/task1ex2.c.s
.PHONY : task1ex2.c.s

task1ex3.o: task1ex3.c.o

.PHONY : task1ex3.o

# target to build an object file
task1ex3.c.o:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f applications/Task1/CMakeFiles/task1ex3.dir/build.make applications/Task1/CMakeFiles/task1ex3.dir/task1ex3.c.o
.PHONY : task1ex3.c.o

task1ex3.i: task1ex3.c.i

.PHONY : task1ex3.i

# target to preprocess a source file
task1ex3.c.i:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f applications/Task1/CMakeFiles/task1ex3.dir/build.make applications/Task1/CMakeFiles/task1ex3.dir/task1ex3.c.i
.PHONY : task1ex3.c.i

task1ex3.s: task1ex3.c.s

.PHONY : task1ex3.s

# target to generate assembly for a file
task1ex3.c.s:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f applications/Task1/CMakeFiles/task1ex3.dir/build.make applications/Task1/CMakeFiles/task1ex3.dir/task1ex3.c.s
.PHONY : task1ex3.c.s

task1ex32.o: task1ex32.c.o

.PHONY : task1ex32.o

# target to build an object file
task1ex32.c.o:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f applications/Task1/CMakeFiles/task1ex32.dir/build.make applications/Task1/CMakeFiles/task1ex32.dir/task1ex32.c.o
.PHONY : task1ex32.c.o

task1ex32.i: task1ex32.c.i

.PHONY : task1ex32.i

# target to preprocess a source file
task1ex32.c.i:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f applications/Task1/CMakeFiles/task1ex32.dir/build.make applications/Task1/CMakeFiles/task1ex32.dir/task1ex32.c.i
.PHONY : task1ex32.c.i

task1ex32.s: task1ex32.c.s

.PHONY : task1ex32.s

# target to generate assembly for a file
task1ex32.c.s:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f applications/Task1/CMakeFiles/task1ex32.dir/build.make applications/Task1/CMakeFiles/task1ex32.dir/task1ex32.c.s
.PHONY : task1ex32.c.s

test.o: test.c.o

.PHONY : test.o

# target to build an object file
test.c.o:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f applications/Task1/CMakeFiles/test.dir/build.make applications/Task1/CMakeFiles/test.dir/test.c.o
.PHONY : test.c.o

test.i: test.c.i

.PHONY : test.i

# target to preprocess a source file
test.c.i:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f applications/Task1/CMakeFiles/test.dir/build.make applications/Task1/CMakeFiles/test.dir/test.c.i
.PHONY : test.c.i

test.s: test.c.s

.PHONY : test.s

# target to generate assembly for a file
test.c.s:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(MAKE) -f applications/Task1/CMakeFiles/test.dir/build.make applications/Task1/CMakeFiles/test.dir/test.c.s
.PHONY : test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... task1ex1"
	@echo "... task1ex2"
	@echo "... task1ex3"
	@echo "... task1ex32"
	@echo "... task1ex1.o"
	@echo "... task1ex1.i"
	@echo "... task1ex1.s"
	@echo "... task1ex2.o"
	@echo "... task1ex2.i"
	@echo "... task1ex2.s"
	@echo "... task1ex3.o"
	@echo "... task1ex3.i"
	@echo "... task1ex3.s"
	@echo "... task1ex32.o"
	@echo "... task1ex32.i"
	@echo "... task1ex32.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /mnt/c/Helen/Uni/COMP105/Simulator_Release_180107/Client && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

